{
 "title": "HTTP Response Monitoring",
 "description": "A very simple and visual Dashboard to monitor HTTP Responses using the native http_response from Telegraf. It just works automatically once the sources are added to telegraf.",
 "tags": [
  "http",
  "http_response"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "url_name",
    "label": "URL",
    "query": {
     "query": "from(bucket:\"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_response\")\n  |> filter(fn: (r) => r[\"_field\"] == \"result_type\")\n  |> filter(fn: (r) => r[\"_value\"] == \"success\")\n  |> group(columns: [\"server\"])\n  |> distinct(column: \"server\")\n  |> keep(columns: [\"_value\"])"
    }
   },
   {
    "name": "error_url",
    "label": "URL with errors",
    "query": {
     "query": "from(bucket: v.defaultBucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_response\")\n  |> filter(fn: (r) => r[\"_field\"] == \"result_type\")\n  |> filter(fn: (r) => r[\"_value\"] != \"success\")\n  |> keep(columns: [\"server\"])\n  |> distinct(column: \"server\")\n  |> group()"
    }
   }
  ]
 },
 "panels": [
  { "title": "Valid URLs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$url_name",
   "type": "stat",
   "description": "Monitoring of the HTTP Response. On the Title of the widget you can find the Website name, and on the value the current response of the HTTP or HTTPS.\n\nThresholds are:\n* Results with 20x , Green\n* Results with 30x , Orange\n* Results with 40x , Red\n* Results with 50x , Blue",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "repeat": "url_name",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_response\")\r\n  |> filter(fn: (r) => r[\"server\"]  =~ /${url_name:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"http_response_code\")\r\n  |> group()\r\n  |> last()",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$url_name$/" }
     ]
    }
   ]
  },
  { "title": "URLs with errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "$error_url",
   "type": "stat",
   "description": "Monitoring of the HTTP Response. On the Title of the widget you can find the Website name, and on the value the current response of the HTTP or HTTPS.\n\nThresholds are:\n* Results with 20x , Green\n* Results with 30x , Orange\n* Results with 40x , Red\n* Results with 50x , Blue",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "repeat": "error_url",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_response\")\r\n  |> filter(fn: (r) => r[\"server\"]  =~ /${error_url:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"result_type\")\r\n  |> filter(fn: (r) => r[\"_value\"] == \"connection_failed\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$url_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Table, and advanced HTTP statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true
  },
  {
   "type": "table",
   "description": "SSL Certificate Monitoring Table. On the first column you can find the SSL x509 Certificate name, and on the second column the TTL/Expirty Date in days.\n\nThresholds are:\n* From 0 days to 14, Red\n* From 15 days to 30, Orange\n* From 31 days onward, Green",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_response\")\r\n  |> filter(fn: (r) => r[\"server\"]  =~ /${url_name:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"http_response_code\")\r\n  |> last()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_response\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"result_type\")\r\n  |> filter(fn: (r) => r[\"_value\"] == \"connection_failed\")\r\n  |> last()"
    }
   ]
  },
  {
   "title": "HTTP Response in ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_response",
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_response\")\r\n  |> filter(fn: (r) => r[\"server\"]  =~ /${url_name:regex}/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"response_time\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
     "select": [
      [
       { "params": [ "response_time" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$url_name$/" }
     ]
    }
   ]
  }
 ]
}